endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\PngWriter
        size: 300
        margin: 10
        encoding: 'UTF-8'
        error_correction_level: 'low'
        round_block_size_mode: 'margin'
        validate_result: false

    #     endroid_qr_code:
    # writer: 'png' # DÃ©faut
    # size: 300
    # margin: 10
